/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package lemiting.tubes;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arcleid
 */
public class Dashboard1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dashboard1
     */
    public Dashboard1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNomor = new javax.swing.JTable();

        jLabel1.setText("ID");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Instansi");

        jLabel3.setText("Nomor");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel4.setText("Deskripsi");

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sapu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabelNomor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "ID", "Instansi", "Nomor", "Deskripsi"
            }
        ));
        tabelNomor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelNomorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelNomor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(jTextField3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String inst = jTextField2.getText();
        String numb = jTextField3.getText();
        String degs = jTextArea1.getText();

        if (inst.equals("") && numb.equals("") && degs.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Data Terlebih Dahulua");
        } else if (numb.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Nomor Telepon Terlebih Dahulu");
        } else if (degs.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Deskripsi Terlebih Dahulua");
        } else if (inst.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Instansi Telepon Terlebih Dahulu");
        } else {
            try {
                String queryy = "INSERT INTO number (agency,number,description) VALUES ('"+inst+"','"+numb+"','"+degs+"')";
                java.sql.Connection vconns = (Connection)koneksiDB.konfigDB();
                java.sql.PreparedStatement s = vconns.prepareStatement(queryy);
                s.execute();
                JOptionPane.showMessageDialog(null, "Tambah Data Berhasil");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Tambah Data");
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            tampilTable();
            sapu_jagad();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String idss = jTextField1.getText();
        String inst = jTextField2.getText();
        String numb = jTextField3.getText();
        String degs = jTextArea1.getText();

        if (inst.equals("") && numb.equals("") && degs.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Data Terlebih Dahulua");
        } else if (numb.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Nomor Telepon Terlebih Dahulu");
        } else if (degs.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Deskripsi Terlebih Dahulu");
        } else if (inst.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Instansi Telepon Terlebih Dahulu");
        } else {
            try {
                //1. Query
                String query = "DELETE FROM number WHERE id = '"+idss+"'";
                //2. Koneksi
                Connection Vconn = (Connection)koneksiDB.konfigDB();
                //3. Statement
                java.sql.PreparedStatement sttmnt = Vconn.prepareStatement(query);
                //4. Eksekusi/Query
                sttmnt.execute(query);
                //5. Notif
                JOptionPane.showMessageDialog(null, "You did it blud.");
                tampilTable();
                sapu_jagad();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Try Harder.");
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String idss = jTextField1.getText();
        String inst = jTextField2.getText();
        String numb = jTextField3.getText();
        String degs = jTextArea1.getText();

        if (inst.equals("") && numb.equals("") && degs.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Data Terlebih Dahulua");
        } else if (numb.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Nomor Telepon Terlebih Dahulu");
        } else if (degs.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Deskripsi Terlebih Dahulu");
        } else if (inst.equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Instansi Telepon Terlebih Dahulu");
        } else {
            try {
                String queryy = "UPDATE number SET id = '"+idss+"', agency = '"+inst+"', number = '"+numb+"', description = '"+degs+"' WHERE id = '"+idss+"'";
                java.sql.Connection vconns = (Connection)koneksiDB.konfigDB();
                java.sql.PreparedStatement s = vconns.prepareStatement(queryy);
                s.execute();
                JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
                tampilTable();
                sapu_jagad();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Edit Data");
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        sapu_jagad();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabelNomorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelNomorMouseClicked
        // TODO add your handling code here:
        int baris = tabelNomor.rowAtPoint(evt.getPoint());

        String digs = tabelNomor.getValueAt(baris, 1).toString();
        jTextField1.setText(digs);

        String ings = tabelNomor.getValueAt(baris, 2).toString();
        jTextField2.setText(ings);

        String nugs = tabelNomor.getValueAt(baris, 3).toString();
        jTextField3.setText(nugs);

        String degs = tabelNomor.getValueAt(baris, 4).toString();
        jTextArea1.setText(degs);
    }//GEN-LAST:event_tabelNomorMouseClicked

        private void tampilTable()
    {
        DefaultTableModel tb = new DefaultTableModel();
        
        tb.addColumn("No");
        tb.addColumn("ID");
        tb.addColumn("Instansi");
        tb.addColumn("Nomor");
        tb.addColumn("Deskripsi");
                
        try {
            int count = 1;
            //1. Query
            String query = "SELECT * FROM number";
            
            //2. Fungsi Koneksi
            java.sql.Connection vconn = (Connection)koneksiDB.konfigDB();
            
            //3. Kirim Parameter Fungsi
            java.sql.Statement s = vconn.createStatement();
            
            //4. Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(query);
            
            //5. Looping
            while (r.next()) {
                tb.addRow(new Object[]{
                    count++,r.getString(1),r.getString(2),r.getString(3),r.getString(4)
                });
            }
            tabelNomor.setModel(tb);
        } catch (Exception e) {
            
        }
    }
    
    private void sapu_jagad() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextArea1.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tabelNomor;
    // End of variables declaration//GEN-END:variables
}
