/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.crud_proj;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arcleid
 */
public class MenuKaryawan extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuKarya
     */
    public MenuKaryawan() {
        initComponents();
        tampilTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKaryawan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Menu Karyawan");

        tabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null},
                {null, "", null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "ID", "Nama", "Alamat"
            }
        ));
        tabelKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKaryawan);

        jLabel1.setText("Nama");

        jLabel2.setText("Alamat");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kota", "Jakarta", "Bandung", "Yogyakarta", "Cirebon", "Aceh", "Alabama" }));

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sapu Jagad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 273, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = jTextField1.getText();
        String adrs = (String) jComboBox1.getSelectedItem();
        
        if (name.equals("") || adrs.equals("Pilih Kota")) {
            JOptionPane.showMessageDialog(null, "Isi Data Terlebih Dahulua");
        } else if (adrs.equals("Pilih Kota")) {
            JOptionPane.showMessageDialog(null, "Pilih Alamat Terlebih Dahulua");
        } else {
            try {
                String queryy = "INSERT INTO karyawan (nama,alamat) VALUES ('"+name+"','"+adrs+"')";
                java.sql.Connection vconns = (Connection)koneksiDB.konfigDB();
                java.sql.PreparedStatement s = vconns.prepareStatement(queryy);
                s.execute();
                JOptionPane.showMessageDialog(null, "Tambah Data Berhasil");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Tambah Data");
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            tampilTable();
            delete();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String ids = jTextField2.getText();
        String nms = jTextField1.getText();
        String ams = (String) jComboBox1.getSelectedItem();
        
        if (nms.equals("") || ams.equals("Pilih Kota")) {
            JOptionPane.showMessageDialog(null, "Isi Data Terlebih Dahulua");
        } else if (ams.equals("Pilih Kota")) {
            JOptionPane.showMessageDialog(null, "Pilih Alamat Terlebih Dahulua");
        } else {
            try {
                String Csql = "UPDATE karyawan SET id = '"+ids+"', nama = '"+nms+"', alamat = '"+ams+"' WHERE id = '"+ids+"'";
                java.sql.Connection Vconn = (Connection)koneksiDB.konfigDB();
                java.sql.PreparedStatement psht = Vconn.prepareStatement(Csql);
                psht.execute();
                JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
                tampilTable();
                delete();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Try Harder Nigga");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }   
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKaryawanMouseClicked
        // TODO add your handling code here:
        int baris = tabelKaryawan.rowAtPoint(evt.getPoint());
        //int kolom = tabelKaryawan.columnAtPoint(evt.getPoint());
        
        String gigs = tabelKaryawan.getValueAt(baris, 1).toString();
        jTextField2.setText(gigs);
        
        String negs = tabelKaryawan.getValueAt(baris, 2).toString();
        jTextField1.setText(negs);
        
        String nigs = tabelKaryawan.getValueAt(baris, 3).toString();
        jComboBox1.setSelectedItem(nigs);
    }//GEN-LAST:event_tabelKaryawanMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String ids = jTextField2.getText();
        String nms = jTextField1.getText();
        String ams = (String) jComboBox1.getSelectedItem();
        
        if (nms.equals("") || ams.equals("Pilih Kota")) {
            JOptionPane.showMessageDialog(null, "Isi Data Terlebih Dahulua");
        } else if (ams.equals("Pilih Kota")) {
            JOptionPane.showMessageDialog(null, "Pilih Alamat Terlebih Dahulua");
        } else {
            try {
               //1. Query
               String query = "DELETE FROM karyawan WHERE id = '"+ids+"'";
               //2. Koneksi
               Connection Vconn = (Connection)koneksiDB.konfigDB();
               //3. Statement
               java.sql.PreparedStatement sttmnt = Vconn.prepareStatement(query);
               //4. Eksekusi/Query
               sttmnt.execute(query);
               //5. Notif
               JOptionPane.showMessageDialog(null, "You did it blud.");
               tampilTable();
               delete();
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Try Harder.");
               JOptionPane.showMessageDialog(null, e.getMessage());
           }   
        }     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tampilTable()
    {
        DefaultTableModel tb = new DefaultTableModel();
        
        tb.addColumn("No");
        tb.addColumn("ID");
        tb.addColumn("Nama");
        tb.addColumn("Alamat");
                
        try {
            int count = 1;
            //1. Query
            String query = "SELECT * FROM karyawan";
            
            //2. Fungsi Koneksi
            java.sql.Connection vconn = (Connection)koneksiDB.konfigDB();
            
            //3. Kirim Parameter Fungsi
            java.sql.Statement s = vconn.createStatement();
            
            //4. Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(query);
            
            //5. Looping
            while (r.next()) {
                tb.addRow(new Object[]{
                    count++,r.getString(1),r.getString(2),r.getString(3)
                });
            }
            tabelKaryawan.setModel(tb);
        } catch (Exception e) {
            
        }
    }
    
    private void delete() {
        jTextField2.setText("");
        jTextField1.setText("");
        jComboBox1.setSelectedIndex(0); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tabelKaryawan;
    // End of variables declaration//GEN-END:variables
}
